import type { Provider } from '@angular/core';
import {
  LucideAlertTriangle,
  LucideArrowLeft,
  LucideArrowRight,
  LucideCalendar,
  LucideCheck,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCopy,
  LucideDatabase,
  LucideEye,
  LucideFileText,
  LucidePlus,
  LucideLogOut,
  LucideMapPin,
  LucideMenu,
  LucideMoreVertical,
  LucidePencil,
  LucidePlane,
  LucideSearch,
  LucideSettings,
  LucideShield,
  LucideTags,
  LucideTrash2,
  LucideUser,
  LucideUserPlus,
  LucideUsers,
  LucideX,
  provideLucideConfig,
  provideLucideIcons,
} from '@lucide/angular';

export function provideAlpenflightIcons(): Provider[] {
  return [
    provideLucideConfig({
      size: 24,
      strokeWidth: 1.5,
      absoluteStrokeWidth: true,
    }),
    provideLucideIcons(
      LucideAlertTriangle,
      LucideArrowLeft,
      LucideArrowRight,
      LucideCalendar,
      LucideCheck,
      LucideChevronDown,
      LucideChevronLeft,
      LucideChevronRight,
      LucideCopy,
      LucideDatabase,
      LucideEye,
      LucideFileText,
      LucidePlus,
      LucideLogOut,
      LucideMapPin,
      LucideMenu,
      LucideMoreVertical,
      LucidePencil,
      LucidePlane,
      LucideSearch,
      LucideSettings,
      LucideShield,
      LucideTags,
      LucideTrash2,
      LucideUser,
      LucideUserPlus,
      LucideUsers,
      LucideX,
    ),
  ];
}
