[versions]
java = "25"
springBoot = "4.1.1"
angular = "22.0.1"
gradle = "9.7.1"
flyway = "13.4.0"
openapiGenerator = "7.25.0"
idb = "8.0.3"
keycloak = "26.7.2"
postgresql = "42.7.13"
springDependencyManagement = "1.1.7"
springdocOpenapi = "3.1.0"
nodeGradlePlugin = "7.1.0"
nodeRuntime = "22.23.2"

[libraries]
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-boot-flyway = { module = "org.springframework.boot:spring-boot-flyway" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdocOpenapi" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "nodeGradlePlugin" }
