spring:
  main:
    banner-mode: off
  application:
    name: alpenflight-server


springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

alpenflight:
  mail:
    enabled: ${ALPENFLIGHT_MAIL_ENABLED:false}
