package ch.alpenflight.migrations.domain;

public enum BundleIngestErrorCode {

    BUNDLE_TOO_LARGE,
    BUNDLE_FORBIDDEN,
    BUNDLE_HANDSHAKE_EXPIRED,
    BUNDLE_ALREADY_CONSUMED,
    BUNDLE_PRIOR_RUN_FAILED,
    BUNDLE_INGEST_IN_PROGRESS,
    BUNDLE_HEADER_MALFORMED,
    BUNDLE_DECRYPT_RSA_UNWRAP_FAILED,
    BUNDLE_DECRYPT_AEAD_TAG_FAILED,
    BUNDLE_TRUNCATED,
    BUNDLE_TAR_PARSE_FAILED,
    BUNDLE_MISSING_ENTRIES,
    BUNDLE_EXTRA_ENTRIES,
    BUNDLE_CROSS_TENANT_FK_LEAK,
    BUNDLE_TIMEOUT,
    MANIFEST_INVALID,
    MANIFEST_EMPTY_CLUBS,
    SCHEMA_VERSION_MISMATCH,
    MAPPER_NOT_AVAILABLE,
    MAPPER_CONSTRAINT_VIOLATION,
    NDJSON_PARSE_FAILED,
    DEPLOYMENT_EXISTS,
    HANDSHAKE_INGEST_IN_PROGRESS,
    DATABASE_CAPACITY_EXCEEDED,
    INGEST_INTERNAL_ERROR
}
