package ch.alpenflight.audit.domain;

public enum AuditAction {
    CREATE,
    UPDATE,
    DELETE,
    STATE_TRANSITION,
    BULK_IMPORT,
    LOOKUP_HIT,
    LOOKUP_MISS,
    MIGRATION_HANDSHAKE_ISSUED,
    MIGRATION_HANDSHAKE_SUPERSEDED,
    MIGRATION_HANDSHAKE_EXPIRED,
    MIGRATION_INGEST_STARTED,
    MIGRATION_INGEST_COMPLETED,
    MIGRATION_INGEST_FAILED,
    PLANNING_NOTIFICATIONS_RUN,
    CLUB_JOIN_CODE_ROTATED,
    CLIENT_IP_REDACTED
}
